name: Create SQL Server RDS with Terraform

permissions:
 id-token: write
 contents: read

on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Make a choice
        options:
        - create
        - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: GitHub_to_AWS_poc
        aws-region: us-east-1
        role-duration-seconds: 3600

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: |
        cd environments/dev 
        terraform init

    - name: Deploy to Development Environment
      id: deploy
      if: ${{ github.event.inputs.action == 'create' }}
      env:
        DB_USERNAME: ${{ secrets.DEV_RDS_USER }}
        SQLCMDPASSWORD: ${{ secrets.DEV_RDS_PASS }}
      run: |
        cd environments/dev
        terraform apply --auto-approve -var="admin_user=${DB_USERNAME}" -var="admin_pass=${SQLCMDPASSWORD}" 
        echo "::set-output name=rds_host1::$(terraform output custom_module_rds_endpoint)"

    - name: Destroy development Environment
      if: ${{ github.event.inputs.action == 'destroy' }}
      env:
        DB_USERNAME: ${{ secrets.DEV_RDS_USER }}
        SQLCMDPASSWORD: ${{ secrets.DEV_RDS_PASS }}
      run: |
        cd environments/dev
        terraform destroy --auto-approve -var="admin_user=${DB_USERNAME}" -var="admin_pass=${SQLCMDPASSWORD}" 

    - name: Run Scrips
      if: ${{ github.event.inputs.action == 'create' }}
      env:
        DB_USERNAME: ${{ secrets.DEV_RDS_USER }}
        SQLCMDPASSWORD: ${{ secrets.DEV_RDS_PASS }}
      run: |
        sqlcmd -U admin -S ${{ steps.deploy.outputs.rds_host1 }},1433 -i query.sql

