name: Create MySQL RDS with Terraform

on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Make a choice
        options:
        - create
        - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }} 
        role-session-name: GitHub_to_AWS_poc
        aws-region: us-east-1
        role-duration-seconds: 3600

    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Deploy to Development Environment
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.choice == 'create' }}
      env:
        DB_USERNAME: ${{ secrets.DEV_RDS_USER }}
        DB_PASSWORD: ${{ secrets.DEV_RDS_PASS }}
      run: |
        cd environments/dev
        terraform apply --auto-approve -var="db_username=${DB_USERNAME}" -var="db_password=${DB_PASSWORD}" 

    - name: Destroy development Environment
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.choice == 'destroy' }}
      run: |
        cd environments/dev
        terraform destroy --auto-approve 